apiVersion: v1
kind: Service
metadata:
  name: hit-record-api-v1-service
  namespace: hitrecord
spec:
  type: ClusterIP
  selector:
    app: hit-record-api-v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 22000