version: '3.9'

networks:
  JenkinsServerNetwork:

services:
  jenkins:
    networks:
      - JenkinsServerNetwork
    environment:
      - TZ=Asia/Dhaka
    restart: on-failure
    image: jenkins/jenkins:latest
    container_name: JenkinsServer
    ports:
      - 8099:8080
    volumes:
      - ~/apps/jenkins:/var/jenkins_home
