name: Docker Image Build and Publish

on:
  release:
    types: [published]

env:
  VERSION: ${{github.ref_name}}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Container image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/hitrecord:${{env.VERSION}}
        docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/hitrecord:latest

    - name: Push the image to Dockerhub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/hitrecord:${{env.VERSION}}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/hitrecord:latest

    - name: Get last tag
      id: get-tag
      shell: bash
      run: |
        api_url="https://hitrecord.fahadahammed.com/api/latest/"
        fallback_version='{"version": "'"$VERSION"'"}'

        response=$(curl -k -s -w "%{http_code}" "$api_url")
        status_code="${response: -3}"  # Extract the last 3 characters, which represent the status code

        if [ "$status_code" -eq 200 ]; then
            LAST_TAG=$(echo "$response" | jq -r '.version')
        else
            LAST_TAG=$(echo "$fallback_version" | jq -r '.version')
        fi
        echo "LAST_TAG=$LAST_TAG" >> $GITHUB_ENV

    - name: Check Variables
      run: |
        echo $VERSION $LAST_TAG