name: Docker Image Build and Publish

on:
  release:
    types: [published]
  push:
    branches:
      - main

env:
  VERSION: ${{github.ref_name}}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the Container image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/hitrecord:${{env.VERSION}}
        docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/hitrecord:latest

    - name: Push the image to Dockerhub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/hitrecord:${{env.VERSION}}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/hitrecord:latest

    - name: Get last tag
      id: get-tag
      shell: bash
      run: |
        LAST_TAG=$(curl -k -s https://hitrecord.fahadahammed.com/api/latest/ | jq -r '.version')
        echo "LAST_TAG=$LAST_TAG" >> $GITHUB_ENV

    - name: Check Variables
      run: |
        echo $VERSION $LAST_TAG
#        echo ${{env.VERSION}}
#        echo ${{env.LAST_TAG}}