name: Docker Image Build and Publish

on:
  release:
    types: [published]

env:
  VERSION: ${{github.ref_name}}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Get last tag
      id: get-tag
      shell: bash
      run: |
        LAST_TAG=$(git describe --tags --abbrev=0 $(git describe --tags --abbrev=0)^)
        echo "Last tag: $LAST_TAG"

    - name: Use the last tag as an output variable
      run: echo "LAST_TAG=${{ steps.get-tag.outputs.LAST_TAG }}" >> $GITHUB_ENV

    - name: Check Variables
      run: |
        echo ${{env.VERSION}}
        echo ${{env.LAST_TAG}}

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/hitrecord:${{env.VERSION}}
        docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/hitrecord:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push the image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/hitrecord:${{env.VERSION}}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/hitrecord:latest