name: Docker Image Build and Publish

on:
  release:
    types: [published]

env:
  VERSION: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/hitrecord:${{env.VERSION}}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/hitrecord:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push the image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/hitrecord:${{env.VERSION}}

    - name: Push the image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/hitrecord:latest